language: node_js
node_js:
- 0.12.7
before_script:
  node app.js & npm installserver & npm startserver &
deploy:
  provider: heroku
  api_key:
    secure: bfnGf/VWEvP7EwkYdP0d3xDQvqH3NLCkDW5+WP0gFLYnoJ7JR9yYMbM2l3ULIDIIp5101GhMWvp8zSTXAO2G++sSoJylVMvvquG1EIaZEdmqc6q00MYhc3lXs/8G0WAaTpGqdn0lYfPBvg5EeQUXLhnUNhdHW7o+7x96kMFp5wQ4HM2R+99sJflQWDo4lZAjUFrq4x25bZdguXGJz8Wmri86D3CqrI7RSV/m6CYSA608ON8vas6MFhVUMPUXOJU1UMSC9PXIaz/wk9YnN3dXCEK4OBMURwP18XWzDyR4KPgEs1f2O5amslCjaVcJ/sCCriaNMNHtL6T/sOh3iABypA5mE8nl2+cHWEJNrkLXBujvLgbE02WO4wdwdn4Cm9AC69FBvnDuN0BgRt3y1J+lV9cdaoFhEzI4PlLOSoNNmZ8czUzgd3zQs2GcvafooIWBvQRlY+N3DSAYMgXDSK8tyHFcmqprOQ0MQlWjIJP+aerBsTvlPRzHH1Tp+9hoe0vc3PsZJUSGX5a9oWwq78spzyFQb+5FgYwgE+4nQEQRI7YDGpZbOp9uibDG7hX5tqSQcOS56b0mTV6GK/uvM3D8BHnx33fr1xKTODgnUEYBvMBy/R20ZtboZQHcPiMCUuwdfDRmLC+cRbdF/IkL8+0huPGwyDQP5gwQ15QtUHz1mQQ=
  app: bennyjrxyz
  on:
    repo: jrbenny35/mywebsitev2
